standardnotes/syncing-server

- .gitignore
- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/api/auth_controller.rb
- config/application.rb
- config/database.yml
- config/environments/docker_development.rb
- config/environments/production.rb
- config/secrets.yml
- env.sample
This PR creates a new `docker_development` rails environment that uses Sqlite3 as a standalone database.
The container can be stood up and running within minutes given the instructions added to the README.
Some conditions inside `config/application.rb` needed to be changed to check if ENV vars were available. It appears you use `AWS_REGION` and `SQS_QUEUE` environment variables but are not managing a list of env vars inside source control. I've moved all the settings to an `env.sample` file that will keep track of all the vars that need tracking.  Instructions on how to use the sample file are included, but you'll just need to copy the file to `.env` and rails will pick it up when booting up.
Please let me know if you have any questions or concerns
Thanks
> Dockerize Server

- Dockerfile
- Gemfile
- Gemfile.lock
- config/database.yml
For #16 
As explained on [this](https://devcenter.heroku.com/articles/sqlite3) article, SQLite is not intended as a production grade database. Instead, Heroku recommends using a production grade database like Postgres, although we are sticking to MySQL.
> Remove sqlite3 usage

- README.md
This PR will add instructions on how to disable the registration for new accounts using docker-compose based on https://github.com/standardfile/ruby-server/issues/74
> Add instructions to disable registrations using docker-compose

- config/secrets.yml
- env.sample
Secrets should be generated and defined by users explicitly in the `.env` file.
> Load secrets from .env file

- env.sample
Fixes #41 , and probably #27, #28 
I know the example env file specifically advises to use `bundle exec rake secret` to generate these secrets, but since no default is given, I thought it might help.
> Changed Example env file

- Dockerfile
When running CMD in quotes the PATH to the script is reset thus resulting in `bundler` not being present in the shell. When running the image the output from the container is:
```
/bin/sh: 1: bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0: not found
```
Removing the quotes fixes the issue
> Fix Docker CMD

- .github/workflows/dev.yml
- .github/workflows/pr.yml
- .github/workflows/prod.yml
- .gitignore
- app/controllers/api/items_controller.rb
- app/controllers/api/revisions_controller.rb
- app/jobs/cleanup_revisions_job.rb
- app/jobs/duplicate_revisions_job.rb
- app/models/item.rb
- app/models/item_revision.rb
- app/models/revision.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20200601101128_add_item_revisions.rb
- db/migrate/20200605085931_add_duplicate_of_to_items.rb
- db/schema.rb
- docker-compose.yml
- lib/sync_engine/abstract/sync_manager.rb
- spec/controllers/api/items_controller_spec.rb
- spec/controllers/api/revisions_controller_spec.rb
- spec/factories/item_revision.rb
- spec/factories/revision.rb
- spec/jobs/cleanup_revisions_job_spec.rb
- spec/jobs/duplicate_revisions_job_spec.rb
- spec/models/item_spec.rb
Whenever an item is saved it will save a new revision of the item.
2 new API endpoints are created for retrieving revisions:
```
GET /items/:item_id/revisions
GET /items/:item_id/revisions/:id
```
Items to Revisions relation is many to many for the purpose of creating duplicates of items and assigning existing revisions to them.
I've also updated the local `docker-compose` setup by:
- mounting the local source code as a volume to the app container (changes in code will reflect in the running container)
- mounting `data/` folder for persisting database entries between container runs
> Add note revisions

- app/models/item.rb
- spec/controllers/api/items_controller_spec.rb
- spec/jobs/cleanup_revisions_job_spec.rb
- spec/jobs/duplicate_revisions_job_spec.rb
as discussed with @mobitar - we should be saving the `n-1` state of the item as a revision the `n` state is preserved in the `item`.
> Fix saving revisions to previous content

- app/controllers/admin/admin_controller.rb
- spec/controllers/admin/admin_controller_spec.rb
Removing the IP checking since it is not the application's responsibility to check the network/security layer. Prevents the applications from scaling out (in particular the source of the requests coming in): https://12factor.net/concurrency
Since we have set up AWS Web Application Firewall to restrict access to that area - this check is redundant.
> Remove admin IP checking from within the application

- Dockerfile
- Dockerfile.worker
- docker/entrypoint.sh
This should fix the issue where server was restarting due to pid lock file being present: https://github.com/standardnotes/syncing-server/issues/68
Also cleans up the Dockerfile and adds a cache layer on the Ruby dependencies in Gemfile
> fix: cleanup docker setup and server pid locking

- docker-compose.yml
- docker/entrypoint.sh
- lib/tasks/migrate_ignore_concurrent.rake
When running multiple containers we encounter an error about database advisory lock:
```
2020-07-02 15:06:52ActiveRecord::ConcurrentMigrationError:
2020-07-02 15:06:52Cannot run migrations because another migration process is currently running.
2020-07-02 15:06:52/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/migration.rb:1315:in `with_advisory_lock'
2020-07-02 15:06:52/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/migration.rb:1148:in `migrate'
2020-07-02 15:06:52/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/migration.rb:1007:in `up'
2020-07-02 15:06:52/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/migration.rb:985:in `migrate'
```
In Rails 6 you can disable the advisory lock to run migrations in an environment where you run multiple …
> fix: Running concurrent migrations in Rails 5.1.7

- app/controllers/api/revisions_controller.rb
- app/models/revision.rb
- spec/controllers/api/revisions_controller_spec.rb
For `/items/:item_id/revisions`
```json
{
"uuid": "<the item's uuid>",
"content_type": "<content type field>",
"revision_uuid": "<the revision's uuid>",
"created_at": "<created_at field>",
"updated_at": "<updated_at field>"
}
```
The goal is to prevent downloading the encrypted content for each revision. We should use `/items/:item_id/revisions/:revision_id` for this.
For `/items/:item_id/revisions/:revision_id`
```json
{
"uuid": "<the item's uuid>",
"items_key_id": "<items_key_id field>",
"duplicate_of": "<duplicate_of field>",
"enc_item_key": "<enc_item_key field>",
"content": "<content field>",
"auth_hash": "<auth_hash field>",
"deleted": "<deleted field>",
"content_type": "<content type field>",
"revision_uuid": "<the revision's uuid>",
"created_at": "<created_at field>", …
```
> fix: server history response

- README.md
Many users trying to self-host do not change the branch from `develop` and get more errors than they should.
This PR changes the clone command to always default to the `master` branch.
Can be merged if approved
> fix: suggest cloning master branch in the readme

- app/controllers/api/api_controller.rb
- app/controllers/api/sessions_controller.rb
- app/controllers/application_controller.rb
Basically, we don't need CSRF because this is a RESTful API server. No cookies are passed along requests; therefore, CSRF attacks are not even possible.
Closes #86
> fix: no csrf

- Dockerfile
Running processes as root is bad practice, following the principle of the least privilege. A process that runs at root in a container runs at root on the host (unless namespaces are used, which is not a common setup). Lots of people are just grabbing from Docker Hub, and passing the `--user` flag at runtime does not work out-of-the-box in that case.
Since we don't really need root privileges even for running the entrypoint script, I suggest we use the `USER` directive. `UID` and `GID` would still be customisable as arguments (`ARG`) so it's fairly convenient.
That works as intended for me, feel free to discuss if you want another approach!
```
$ docker exec -ti snotes ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   1584     4 ? …
```
> fix: run docker without root

- app/controllers/api/auth_controller.rb
- config/application.rb
- config/environments/development.rb
- config/shoryuken.yml
- env.sample
Rails 5 Active Job default adapter is `:async`: https://blog.bigbinary.com/2016/03/29/rails-5-changed-default-active-job-adapter-to-async.html
This change fixes the issue where someone would have to have `AWS_REGION` environment variable set in order to have the queue processed in `RAILS_ENV=production`. This was due to the fact that `shoryuken` was the default queue adapter.
> feat: make async the default active job queue adapter

- app/controllers/api/api_controller.rb
- app/controllers/api/auth_controller.rb
- app/jobs/extension_job.rb
- app/mailers/archive_mailer.rb
- app/models/user.rb
- config/sn_session.yml
- db/migrate/20200916205444_add_key_param_fields.rb
- db/schema.rb
- env.sample
- lib/sync_engine/2020_01_15/user_manager.rb
- lib/sync_engine/abstract/user_manager.rb
- spec/controllers/api/auth_controller_spec.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- Renames auth params to key params
- If accessing key params endpoint with valid session, returns additional data, including the origination of the key params (registration, password-change, etc) and a created timestamp in string format (number of seconds since epoch)
- Introduces new ENV variable `PSEUDO_KEY_PARAMS_KEY` to use for pseudo params instead of `Rails.application.secrets.secret_key_base`
> feat: key params with additional authenticated values

- lib/sync_engine/2016_12_15/sync_manager.rb
- lib/sync_engine/2019_05_20/sync_manager.rb
- lib/sync_engine/abstract/sync_manager.rb
- spec/controllers/api/items_controller_spec.rb
- spec/factories/items.rb
In new and old API versions, always save `items_key_id` and `auth_hash` field values, even if they're not present.
> feat: set a value for items_key_id and auth_hash if not provided in a request

- .env.sample
- .github/workflows/dev.yml
- .github/workflows/pr.yml
- .github/workflows/prod.yml
- Gemfile
- Gemfile.lock
- app/jobs/cleanup_revisions_job.rb
- app/jobs/duplicate_revisions_job.rb
- app/jobs/extension_job.rb
- config/database.yml
This (along with infra changes) will allow the `SELECT ...` queries to be directed to the database read replica node instead of the primary node in order to reduce the heavy lifting on the primary db. 
For now (starting small) it only applies to 3 jobs: cleanup revisions job, extensions job and duplicate revisions job.
> Add support for using database read replicas

- app/controllers/api/revisions_controller.rb
with the usage of `distribute_reads` revisions will be read from the read replica if available, to take some of the heavy lifting from the primary db.
> feat: read revisions from the database read replica

- .env.sample
- app/controllers/api/revisions_controller.rb
- app/models/item.rb
- app/models/user.rb
- docker/entrypoint.sh
- lib/tasks/cleanup_revisions.rake
- spec/controllers/api/items_controller_spec.rb
- spec/tasks/cleanup_revisions.rb
The idea is to run the `revisions_cleanup` rake task on every let's say 30 minutes and it will pick up items updated during last hour and clean their revisions. I'm open for suggestions in terms of adjusting these params.
> Refactor revisions cleanup

- app/controllers/admin/admin_controller.rb
- app/jobs/account_cleanup_job.rb
- spec/controllers/admin/admin_controller_spec.rb
- spec/jobs/account_cleanup_job.rb
When an account has a lot of items (for example we had a test account that had 8k items) the process of deleting account with all it's items and revisions takes too long to be completed withing a single request - thus a user cannot reset his account. 
Delegated the items/revisions cleanup to an async job that is done after the user deletes the account.
> fix: deleting accounts with large number of items

- app/models/item.rb
- app/models/user.rb
- lib/sync_engine/2016_12_15/sync_manager.rb
- lib/sync_engine/2019_05_20/sync_manager.rb
- lib/sync_engine/2020_01_15/sync_manager.rb
- spec/controllers/api/items_controller_spec.rb
Prior to this change, the server was somewhat liberal with did not constitute a conflict. Any changes that were within 1 second apart would not conflict. This means naturally that if there are indeed different contents, but somehow performed within 500ms apart, a stale copy could overwrite the server value.
This version reduces this threshold to the microsecond scale. Instead of a liberal interval of 1s, we instead allow only a maximum of 1000 microseconds (1 millisecond). Any changes greater than 1ms apart are automatically conflicted. This is a much stricter conflicting strategy, so could theoretically result in greater conflicts created, if the clients are not precisely tracking server dates. But this should not be the case.
> fix: more precise sync date conflict handling
